import React, { useEffect } from 'react'
import styles from 'styles/OverView.module.css'
import TimeCard from './UI/TimeCard'
import ApplyButton from './UI/ApplyButton'
import { useAccount } from 'wagmi'
const Overview = () => {
  return (
    <div className={styles.container}>
      <p className={styles.tittle} style={{ paddingTop: '80px' }}>mock hackthon</p>
      <p className={styles.Stittle}>The first Onchain Hackathon</p>
      <p className={styles.desc}>
        mock hackthon is the first onchain hackathon base Competition Protocol for all ethereum developers to promote the development of the ethereum ecosystem.
        The hackathon prizes distribute by Chain-link Automation, and the lucky voters generated by Chian-link VRF  may get the special prizes.</p>
      <TimeCard />
      <ApplyButton />
    </div>
  )
}

export default Overview